web:
  port: :8084
  time: 2024-1-30
  host: 127.0.0.1:8084
  protocol: http
mysql:
  host: 127.0.0.1
  port: 3306
  database: test
  username: root
  password: Cherry1145
  charset: utf8mb3
jwt:
  token: helloWorld
  issuer: ""
redis:
  addr:  localhost
  password:
  db: 0
  poolsize: 10
email:
  account: ""
  password: ""
kafka:
  topic1: ""
  topic2: ""
  host: ""
  timeOut: ""
model:
  AccessKey: ""
  SecretKey: ""