// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/c/all": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "获取所有班级ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/info": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "获取班级信息",
                "parameters": [
                    {
                        "description": "班级ID列表",
                        "name": "classIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/mg/add": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "加入班级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "班级验证码",
                        "name": "classToken",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/mg/clear": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "将学生请出班级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "studentID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/mg/quit": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "离开班级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/mg/score": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "查询班级某次考试的成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/mg/sh": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "查询班级最近n次的考试成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "查询的数目",
                        "name": "n",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/new": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "创建班级",
                "parameters": [
                    {
                        "description": "班级信息",
                        "name": "classMg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ClassJson"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/c/rc": {
            "post": {
                "tags": [
                    "Class"
                ],
                "summary": "修改班级信息",
                "parameters": [
                    {
                        "description": "班级信息",
                        "name": "classMg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ClassJson"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/all": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "获取所有考试ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/delete": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "删除考试",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/info": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "获取考试信息",
                "parameters": [
                    {
                        "description": "考试ID列表",
                        "name": "examIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/mg/join": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "班级加入考试",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/mg/num": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "获取考试相关的数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据类型 student teacher task",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/mg/plan": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "分发考试任务",
                "parameters": [
                    {
                        "description": "改卷任务分段点数组",
                        "name": "cut",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CutMg"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/mg/quit": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "班级退出考试",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "班级ID",
                        "name": "classID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/mg/score": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "获取某一考试所有人的考试成绩",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/new": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "创建考试",
                "parameters": [
                    {
                        "description": "考试信息",
                        "name": "exam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Exam"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/exam/re": {
            "post": {
                "tags": [
                    "Exam"
                ],
                "summary": "修改考试信息",
                "parameters": [
                    {
                        "description": "考试信息",
                        "name": "exam",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Exam"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/all": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "获取所有试卷的ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/delete": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "删除试卷",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "试卷ID",
                        "name": "paperID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/info": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "获取试卷信息",
                "parameters": [
                    {
                        "description": "试卷ID列表",
                        "name": "paperIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/na": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "添加试卷答案",
                "parameters": [
                    {
                        "description": "试卷信息列表",
                        "name": "answers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AnswerJson"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/new": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "添加试卷",
                "parameters": [
                    {
                        "description": "试卷信息列表",
                        "name": "papers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.PaperJson"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/paper/sum": {
            "post": {
                "tags": [
                    "Paper"
                ],
                "summary": "更新试卷的总分",
                "parameters": [
                    {
                        "description": "试卷ID",
                        "name": "paperIDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/as": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "获取试卷答案",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/mark": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "为单题打分",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "部分试卷ID",
                        "name": "partID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分数",
                        "name": "mark",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/mission": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "获取改卷任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/ms/exam": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "查看所在考试",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/ms/fm": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "完成阅卷任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/seisei/ms/part": {
            "post": {
                "tags": [
                    "Teacher"
                ],
                "summary": "按任务阅卷",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "考试ID",
                        "name": "examID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/stu/scores": {
            "post": {
                "tags": [
                    "student"
                ],
                "summary": "获取学生成绩",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Upload"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件数据",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件类型 paper avatar answer",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/user/all": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "获取用户ID列表",
                "responses": {}
            }
        },
        "/api/user/c": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "获取用户所在的班级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/check": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "检验用户名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/info": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/list": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "用户信息列表",
                "parameters": [
                    {
                        "description": "用户ID列表",
                        "name": "IDs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "passWord",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/new": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "ud",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserJson"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/rv": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "用户修改信息",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "ud",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserJson"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/user/verify": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "用户验证",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "邮箱",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.AnswerJson": {
            "type": "object",
            "properties": {
                "examID": {
                    "type": "integer"
                },
                "img": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.ClassJson": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "teacherID": {
                    "type": "integer"
                }
            }
        },
        "model.CutMg": {
            "type": "object",
            "properties": {
                "cut": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "examID": {
                    "type": "string"
                }
            }
        },
        "model.Exam": {
            "type": "object",
            "properties": {
                "createTime": {
                    "type": "integer"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "state": {
                    "type": "integer"
                },
                "subjects": {
                    "type": "string"
                }
            }
        },
        "model.PaperJson": {
            "type": "object",
            "properties": {
                "examID": {
                    "type": "integer"
                },
                "imgs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "maxMark": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "ownerID": {
                    "type": "integer"
                }
            }
        },
        "model.UserJson": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "captcha": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passWord": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string",
                    "example": "0"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
